spring.application.name=buddyrental

spring.datasource.url=jdbc:h2:mem:buddyrental
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update


jwt.secret=p1u2n3e4e5t6a1g2n3i4h5o6t7r8i9s1
jwt.expiration=86400000