spring.application.name=buddyrental

spring.datasource.url=jdbc:h2:mem:buddyrental
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=@P1u2n3e4e5t6

spring.jpa.hibernate.ddl-auto=update

jwt.secret=TXlTdXBlclNlY3VyZUpXVFNlY3JldEtleUZvckhTMjU2QWxnb3JpdGhtMTIzNDU2Nzg5
jwt.expiration=86400000

server.port=${PORT:8080}